In [1]:
import pandas as pd
import numpy as np

In [2]:
htrain=pd.read_csv(r'E:\pythoncode\ML Bootcamp Projects\House Grade Prediction\TRAINING.csv',header=0,index_col=0)

In [3]:
htrain.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           305    8.0        2.0          1.0         3.0   NO         0.0   
2           344    6.0        7.0          7.0         8.0   no         0.0   
3           294    8.0        4.0          3.0         4.0  yes        97.0   
4           328    5.0        4.0          2.0         4.0   NO         0.0   
5           295    9.0        5.0          3.0         5.0  NaN         NaN   

    Lawn(Area)  Nfloors   API  ANB Grade EXPECTED  
id                                                 
1         76.0        2  63.0    4     D    3826$  
2         83.0        7  97.0    1     B    4458$  
3         78.0        1  88.0    4     C    4199$  
4         91.0        5  86.0    1     D    3462$  
5         97.0        4  93.0    3     C    4543$

In [4]:
htrain.shape

(7000, 13)

In [5]:
htrain.isnull().sum()

Area(total)       0
Troom             2
Nbedrooms         3
Nbwashrooms       2
Twashrooms        1
roof           1353
Roof(Area)     1353
Lawn(Area)        2
Nfloors           0
API               1
ANB               0
Grade             0
EXPECTED          0
dtype: int64

In [6]:
htrain.columns

Index(['Area(total)', 'Troom', 'Nbedrooms', 'Nbwashrooms', 'Twashrooms',
       'roof', 'Roof(Area)', 'Lawn(Area)', 'Nfloors', 'API', 'ANB', 'Grade',
       'EXPECTED'],
      dtype='object')

In [7]:
htrain.dtypes

Area(total)      int64
Troom          float64
Nbedrooms      float64
Nbwashrooms    float64
Twashrooms     float64
roof            object
Roof(Area)     float64
Lawn(Area)     float64
Nfloors          int64
API            float64
ANB              int64
Grade           object
EXPECTED        object
dtype: object

In [8]:
#replace the missing values with mean values
for value in ['Troom', 'Nbedrooms', 'Nbwashrooms', 'Twashrooms','Roof(Area)', 'Lawn(Area)','API']:
    htrain[value].fillna(htrain[value].mean(),inplace=True)

In [9]:
htrain.isnull().sum()

Area(total)       0
Troom             0
Nbedrooms         0
Nbwashrooms       0
Twashrooms        0
roof           1353
Roof(Area)        0
Lawn(Area)        0
Nfloors           0
API               0
ANB               0
Grade             0
EXPECTED          0
dtype: int64

In [10]:
htrain.roof.value_counts()

no     1436
NO     1419
yes    1413
YES    1379
Name: roof, dtype: int64

In [11]:
htrain.roof=htrain.roof.map({"yes":"YES","no":"NO","NO":"NO","YES":"YES"})
htrain.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           305    8.0        2.0          1.0         3.0   NO    0.000000   
2           344    6.0        7.0          7.0         8.0   NO    0.000000   
3           294    8.0        4.0          3.0         4.0  YES   97.000000   
4           328    5.0        4.0          2.0         4.0   NO    0.000000   
5           295    9.0        5.0          3.0         5.0  NaN   47.202763   

    Lawn(Area)  Nfloors   API  ANB Grade EXPECTED  
id                                                 
1         76.0        2  63.0    4     D    3826$  
2         83.0        7  97.0    1     B    4458$  
3         78.0        1  88.0    4     C    4199$  
4         91.0        5  86.0    1     D    3462$  
5         97.0        4  93.0    3     C    4543$

In [12]:
#replace the missing values with mode values
for value in ['roof']:
    htrain[value].fillna(htrain[value].mode()[0],inplace=True)

In [13]:
htrain.roof.mode()[0]

'NO'

In [14]:
htrain.isnull().sum()

Area(total)    0
Troom          0
Nbedrooms      0
Nbwashrooms    0
Twashrooms     0
roof           0
Roof(Area)     0
Lawn(Area)     0
Nfloors        0
API            0
ANB            0
Grade          0
EXPECTED       0
dtype: int64

In [15]:
htrain.dtypes

Area(total)      int64
Troom          float64
Nbedrooms      float64
Nbwashrooms    float64
Twashrooms     float64
roof            object
Roof(Area)     float64
Lawn(Area)     float64
Nfloors          int64
API            float64
ANB              int64
Grade           object
EXPECTED        object
dtype: object

In [16]:
htrain['EXPECTED'] = htrain['EXPECTED'].str.replace('$', '').astype(int)

In [17]:
htrain.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           305    8.0        2.0          1.0         3.0   NO    0.000000   
2           344    6.0        7.0          7.0         8.0   NO    0.000000   
3           294    8.0        4.0          3.0         4.0  YES   97.000000   
4           328    5.0        4.0          2.0         4.0   NO    0.000000   
5           295    9.0        5.0          3.0         5.0   NO   47.202763   

    Lawn(Area)  Nfloors   API  ANB Grade  EXPECTED  
id                                                  
1         76.0        2  63.0    4     D      3826  
2         83.0        7  97.0    1     B      4458  
3         78.0        1  88.0    4     C      4199  
4         91.0        5  86.0    1     D      3462  
5         97.0        4  93.0    3     C      4543

In [18]:
htrain.Grade.value_counts()

C    2928
D    2129
B    1475
A     442
E      26
Name: Grade, dtype: int64

In [19]:
colname=['roof','Grade']

In [20]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

for x in colname:
    htrain[x]=le.fit_transform(htrain[x])

In [21]:
htrain.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms  roof  Roof(Area)  \
id                                                                             
1           305    8.0        2.0          1.0         3.0     0    0.000000   
2           344    6.0        7.0          7.0         8.0     0    0.000000   
3           294    8.0        4.0          3.0         4.0     1   97.000000   
4           328    5.0        4.0          2.0         4.0     0    0.000000   
5           295    9.0        5.0          3.0         5.0     0   47.202763   

    Lawn(Area)  Nfloors   API  ANB  Grade  EXPECTED  
id                                                   
1         76.0        2  63.0    4      3      3826  
2         83.0        7  97.0    1      1      4458  
3         78.0        1  88.0    4      2      4199  
4         91.0        5  86.0    1      3      3462  
5         97.0        4  93.0    3      2      4543

In [22]:
htrain.shape

(7000, 13)

In [23]:
for x in colname:
    htrain[x]=le.fit_transform(htrain[x])
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print('Feature', x)
    print('mapping', le_name_mapping)

Feature roof
mapping {0: 0, 1: 1}
Feature Grade
mapping {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}


In [24]:
neworder = ['Area(total)', 'Troom', 'Nbedrooms', 'Nbwashrooms', 'Twashrooms','roof',
       'Roof(Area)', 'Lawn(Area)', 'Nfloors', 'API', 'ANB','EXPECTED','Grade']
htrain=htrain.reindex(columns=neworder)

In [25]:
htrain.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms  roof  Roof(Area)  \
id                                                                             
1           305    8.0        2.0          1.0         3.0     0    0.000000   
2           344    6.0        7.0          7.0         8.0     0    0.000000   
3           294    8.0        4.0          3.0         4.0     1   97.000000   
4           328    5.0        4.0          2.0         4.0     0    0.000000   
5           295    9.0        5.0          3.0         5.0     0   47.202763   

    Lawn(Area)  Nfloors   API  ANB  EXPECTED  Grade  
id                                                   
1         76.0        2  63.0    4      3826      3  
2         83.0        7  97.0    1      4458      1  
3         78.0        1  88.0    4      4199      2  
4         91.0        5  86.0    1      3462      3  
5         97.0        4  93.0    3      4543      2

In [26]:
X = htrain.values[:,:-1]
Y = htrain.values[:,-1]

In [27]:
X.shape

(7000, 12)

In [28]:
Y.shape

(7000,)

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
print(X)

[[-0.98425512  0.69579072 -1.81044525 ... -1.34807597  0.29716957
  -0.42389823]
 [ 0.91363685 -0.71290115  1.21445694 ...  1.52094084 -1.46719601
   0.84908326]
 [-1.51955799  0.69579072 -0.60048437 ...  0.76149522  0.29716957
   0.32740255]
 ...
 [-0.93559122 -0.71290115 -0.60048437 ...  1.436558    0.29716957
  -0.4178556 ]
 [ 0.62165347  0.69579072  1.21445694 ...  0.42396383 -1.46719601
   0.9095096 ]
 [-0.54628005 -1.41724709  0.60947651 ...  1.436558   -0.87907415
  -1.24569642]]


In [30]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
random_state=10)

In [31]:
#predicting using the KNeighbors_Classifier
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=19, metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(2.0, 2.0), (0.0, 1.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (1.0, 2.0), (2.0, 3.0), (1.0, 1.0), (3.0, 3.0), (3.0, 3.0), (0.0, 1.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (0.0, 1.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (0.0, 1.0), (2.0, 2.0), (1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (3.0, 3.0), (1.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 1.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (3.0, 3.0), (1.0, 2.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (3.0, 3.0), (0.0, 0.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 1.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (2.0, 2.0), (1.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (0.

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 76  52   0   0   0]
 [  8 356  95   0   0]
 [  0  27 794  48   0]
 [  0   0  54 582   0]
 [  0   0   0   8   0]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.90      0.59      0.72       128
         1.0       0.82      0.78      0.80       459
         2.0       0.84      0.91      0.88       869
         3.0       0.91      0.92      0.91       636
         4.0       0.00      0.00      0.00         8

    accuracy                           0.86      2100
   macro avg       0.70      0.64      0.66      2100
weighted avg       0.86      0.86      0.86      2100

Accuracy of the model:  0.8609523809523809


E:\ANACONDAP\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
from sklearn import svm
svc_model=svm.SVC(kernel='rbf',C=1.0,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[108  20   0   0   0]
 [ 12 412  35   0   0]
 [  0  23 828  18   0]
 [  0   0  22 614   0]
 [  0   0   0   8   0]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.90      0.84      0.87       128
         1.0       0.91      0.90      0.90       459
         2.0       0.94      0.95      0.94       869
         3.0       0.96      0.97      0.96       636
         4.0       0.00      0.00      0.00         8

    accuracy                           0.93      2100
   macro avg       0.74      0.73      0.74      2100
weighted avg       0.93      0.93      0.93      2100

Accuracy of the model:  0.9342857142857143


E:\ANACONDAP\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [35]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 89  39   0   0   0]
 [ 45 321  92   1   0]
 [  1  83 685 100   0]
 [  0   0  76 559   1]
 [  0   0   0   4   4]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.66      0.70      0.68       128
         1.0       0.72      0.70      0.71       459
         2.0       0.80      0.79      0.80       869
         3.0       0.84      0.88      0.86       636
         4.0       0.80      0.50      0.62         8

    accuracy                           0.79      2100
   macro avg       0.77      0.71      0.73      2100
weighted avg       0.79      0.79      0.79      2100

Accuracy of the model:  0.7895238095238095


In [37]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[101  27   0   0   0]
 [  8 384  67   0   0]
 [  0  41 797  31   0]
 [  0   0  63 573   0]
 [  0   0   0   4   4]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.93      0.79      0.85       128
         1.0       0.85      0.84      0.84       459
         2.0       0.86      0.92      0.89       869
         3.0       0.94      0.90      0.92       636
         4.0       1.00      0.50      0.67         8

    accuracy                           0.89      2100
   macro avg       0.92      0.79      0.83      2100
weighted avg       0.89      0.89      0.89      2100

Accuracy of the model:  0.8852380952380953


In [39]:
htest=pd.read_csv(r'E:\pythoncode\ML Bootcamp Projects\House Grade Prediction\TEST.csv',header=0,index_col=0)

In [40]:
htest.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           348    9.0        5.0          3.0           5  NaN         NaN   
2           311    6.0        5.0          5.0           6   NO         0.0   
3           342    5.0        6.0          6.0           7  yes       120.0   
4           329    7.0        7.0          4.0           6  NaN         NaN   
5           307    6.0        2.0          3.0           4   no         0.0   

    Lawn(Area)  Nfloors   API  ANB EXPECTED  
id                                           
1         84.0        5  91.0    6    4422$  
2         86.0        6  83.0    4    3432$  
3         85.0        4  95.0    5    4066$  
4        105.0        5  97.0    6    4322$  
5         76.0        2  64.0    4    3031$

In [41]:
htest.shape

(3299, 12)

In [42]:
htest.isnull().sum()

Area(total)      0
Troom            1
Nbedrooms        1
Nbwashrooms      1
Twashrooms       0
roof           653
Roof(Area)     653
Lawn(Area)       1
Nfloors          0
API              1
ANB              0
EXPECTED         0
dtype: int64

In [43]:
#replace the missing values with mean values
for value in ['Troom', 'Nbedrooms', 'Nbwashrooms','Roof(Area)', 'Lawn(Area)','API']:
    htest[value].fillna(htest[value].mean(),inplace=True)

In [44]:
htest.isnull().sum()

Area(total)      0
Troom            0
Nbedrooms        0
Nbwashrooms      0
Twashrooms       0
roof           653
Roof(Area)       0
Lawn(Area)       0
Nfloors          0
API              0
ANB              0
EXPECTED         0
dtype: int64

In [45]:
htest.roof=htest.roof.map({"yes":"YES","no":"NO","NO":"NO","YES":"YES"})
htest.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           348    9.0        5.0          3.0           5  NaN   47.267196   
2           311    6.0        5.0          5.0           6   NO    0.000000   
3           342    5.0        6.0          6.0           7  YES  120.000000   
4           329    7.0        7.0          4.0           6  NaN   47.267196   
5           307    6.0        2.0          3.0           4   NO    0.000000   

    Lawn(Area)  Nfloors   API  ANB EXPECTED  
id                                           
1         84.0        5  91.0    6    4422$  
2         86.0        6  83.0    4    3432$  
3         85.0        4  95.0    5    4066$  
4        105.0        5  97.0    6    4322$  
5         76.0        2  64.0    4    3031$

In [46]:
#replace the missing values with mode values
for value in ['roof']:
    htest[value].fillna(htest[value].mode()[0],inplace=True)

In [47]:
htest.isnull().sum()

Area(total)    0
Troom          0
Nbedrooms      0
Nbwashrooms    0
Twashrooms     0
roof           0
Roof(Area)     0
Lawn(Area)     0
Nfloors        0
API            0
ANB            0
EXPECTED       0
dtype: int64

In [48]:
htest.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           348    9.0        5.0          3.0           5   NO   47.267196   
2           311    6.0        5.0          5.0           6   NO    0.000000   
3           342    5.0        6.0          6.0           7  YES  120.000000   
4           329    7.0        7.0          4.0           6   NO   47.267196   
5           307    6.0        2.0          3.0           4   NO    0.000000   

    Lawn(Area)  Nfloors   API  ANB EXPECTED  
id                                           
1         84.0        5  91.0    6    4422$  
2         86.0        6  83.0    4    3432$  
3         85.0        4  95.0    5    4066$  
4        105.0        5  97.0    6    4322$  
5         76.0        2  64.0    4    3031$

In [49]:
htest['EXPECTED'] = htest['EXPECTED'].str.replace('$', '').astype(int)

In [50]:
htest.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  Roof(Area)  \
id                                                                            
1           348    9.0        5.0          3.0           5   NO   47.267196   
2           311    6.0        5.0          5.0           6   NO    0.000000   
3           342    5.0        6.0          6.0           7  YES  120.000000   
4           329    7.0        7.0          4.0           6   NO   47.267196   
5           307    6.0        2.0          3.0           4   NO    0.000000   

    Lawn(Area)  Nfloors   API  ANB  EXPECTED  
id                                            
1         84.0        5  91.0    6      4422  
2         86.0        6  83.0    4      3432  
3         85.0        4  95.0    5      4066  
4        105.0        5  97.0    6      4322  
5         76.0        2  64.0    4      3031

In [52]:
colname=['roof']

In [53]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

for x in colname:
    htest[x]=le.fit_transform(htest[x])

In [54]:
htest.head()

Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms  roof  Roof(Area)  \
id                                                                             
1           348    9.0        5.0          3.0           5     0   47.267196   
2           311    6.0        5.0          5.0           6     0    0.000000   
3           342    5.0        6.0          6.0           7     1  120.000000   
4           329    7.0        7.0          4.0           6     0   47.267196   
5           307    6.0        2.0          3.0           4     0    0.000000   

    Lawn(Area)  Nfloors   API  ANB  EXPECTED  
id                                            
1         84.0        5  91.0    6      4422  
2         86.0        6  83.0    4      3432  
3         85.0        4  95.0    5      4066  
4        105.0        5  97.0    6      4322  
5         76.0        2  64.0    4      3031

In [55]:
X_test_new = htest.values[:,:]

In [56]:
X_test_new.shape

(3299, 12)

In [57]:
X_test_new = scaler.transform(X_test_new)

In [58]:
Y_pred=model_RandomForest.predict(X_test_new)

In [59]:
print(Y_pred)

[1. 3. 2. ... 2. 3. 3.]


In [60]:
model_RandomForest.score(X_train,Y_train)

1.0

In [62]:
testnew=pd.read_csv(r'E:\pythoncode\ML Bootcamp Projects\House Grade Prediction\TEST.csv')
testnew["PREDICTION"]=Y_pred
testnew.head()

id  Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  \
0   1          348    9.0        5.0          3.0           5  NaN   
1   2          311    6.0        5.0          5.0           6   NO   
2   3          342    5.0        6.0          6.0           7  yes   
3   4          329    7.0        7.0          4.0           6  NaN   
4   5          307    6.0        2.0          3.0           4   no   

   Roof(Area)  Lawn(Area)  Nfloors   API  ANB EXPECTED  PREDICTION  
0         NaN        84.0        5  91.0    6    4422$         1.0  
1         0.0        86.0        6  83.0    4    3432$         3.0  
2       120.0        85.0        4  95.0    5    4066$         2.0  
3         NaN       105.0        5  97.0    6    4322$         2.0  
4         0.0        76.0        2  64.0    4    3031$         3.0

In [65]:
testnew.PREDICTION=testnew.PREDICTION.map({0.0:"A",1.0:"B",2.0:"C",3.0:"D",4.0:"E"})
testnew.head()

id  Area(total)  Troom  Nbedrooms  Nbwashrooms  Twashrooms roof  \
0   1          348    9.0        5.0          3.0           5  NaN   
1   2          311    6.0        5.0          5.0           6   NO   
2   3          342    5.0        6.0          6.0           7  yes   
3   4          329    7.0        7.0          4.0           6  NaN   
4   5          307    6.0        2.0          3.0           4   no   

   Roof(Area)  Lawn(Area)  Nfloors   API  ANB EXPECTED PREDICTION  
0         NaN        84.0        5  91.0    6    4422$          B  
1         0.0        86.0        6  83.0    4    3432$          D  
2       120.0        85.0        4  95.0    5    4066$          C  
3         NaN       105.0        5  97.0    6    4322$          C  
4         0.0        76.0        2  64.0    4    3031$          D

In [66]:
testnew.to_excel("HOUSE.xlsx")